import { Kantumruy_Pro } from "next/font/google";
import "./globals.css";

const kantumruyPro = Kantumruy_Pro({
  variable: "--font-body", // Match the Tailwind class name
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata = {
  title: "ស្មៀន / Smean",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${kantumruyPro.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
